version: 2

sources:
  - name: bronze
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: orders
        columns:
          - name: id
            data_tests:
              - not_null
              - unique
          - name: product_id 
            data_tests:
              - relationships:
                  arguments:
                    to: products
                    field: id
        #config:
        #  freshness:
        #    warn_after: 
        #      count: 365
        #      period: day
        #    error_after:
        #      count: 1000
        #      period: day
        #  loaded_at_field: created_at 
      - name: products
        columns:
          - name: id 
            data_tests:
              - unique:
                  config:
                    severity: warn
              - not_null:
                  config:
                    severity: warn
      - name: users
        columns:
          - name: id 
            data_tests:
              - unique:
                  config:
                    severity: warn
              - not_null:
                  config:
                    severity: warn

      - name: reviews
        columns:
          - name: id 
            data_tests:
              - unique:
                  config:
                    severity: warn
              - not_null:
                  config:
                    severity: warn
          - name: product_id
            data_tests:
              - relationships:
                  arguments:
                    to: products
                    field: id  
